---
version: 2.13.0
slug: openthread_border_router
name: OpenThread Border Router(TBR-2)
description: OpenThread Border Router add-on
url: >-
  https://github.com/raphael1688dev/TBR-2/openthread_border_router
arch:
  - aarch64
  - amd64
homeassistant: 2023.9.0
#gpio: true
gpio: false
hassio_api: true
discovery:
  - otbr
# IPC is only used within the Add-on
#host_ipc: false
host_ipc: true
host_network: true
#host_network: false
host_uts: true
#privileged: true
privileged:
  - IPC_LOCK
  - NET_ADMIN
devices:
  - /dev/net/tun
#devices:
#  - /dev/net/tun:/dev/net/tun
#image: homeassistant/{arch}-addon-otbr
init: false
options:
  device: null
  baudrate: "460800"
  flow_control: true
  autoflash_firmware: false
  otbr_log_level: notice
  firewall: false
  nat64: false
  network_device: null
ports:
  8280/tcp: null
  8281/tcp: null
ports_description:
  8280/tcp: OpenThread Web port
  8281/tcp: OpenThread REST API port
schema:
  device: str?
  baudrate: list(57600|115200|230400|460800|921600)
  flow_control: bool
  network_device: str?
  autoflash_firmware: bool
  otbr_log_level: list(debug|info|notice|warning|error|critical|alert|emergency)
  firewall: bool
  nat64: bool
startup: services
